// FOSTER ALUMNI — EDIT HERE
// Add kittens only after adoption is confirmed and the adoption date is recorded.
// Use YYYY-MM-DD dates and image paths from assets/kittens/ when available.
// Set companionId to the other alumnus's id when kittens were adopted together.
const alumniRoot = typeof window !== "undefined" ? window : globalThis;

alumniRoot.PAWS_FOSTER_ALUMNI = [
  {
    id: "freddy",
    status: "Adopted",
    name: "Freddy",
    gender: "Male",
    birthday: "2025-04-02",
    adoptionDate: "2025-08-09",
    fosterLitter: 7,
    image: "assets/kittens/alumni-freddy.png",
    photos: [],
    companionId: "frannie"
  },
  {
    id: "frannie",
    status: "Adopted",
    name: "Frannie",
    gender: "Female",
    birthday: "2025-04-02",
    adoptionDate: "2025-08-09",
    fosterLitter: 7,
    image: "assets/kittens/alumni-frannie.png",
    photos: [],
    companionId: "freddy"
  },
  {
    id: "skylar",
    status: "Adopted",
    name: "Skylar",
    gender: "Female",
    birthday: "2025-04-02",
    adoptionDate: "2026-03-07",
    fosterLitter: 7,
    image: "assets/kittens/alumni-scout.png",
    photos: [],
    secondChance: true
  },
  {
    id: "scout",
    status: "Adopted",
    name: "Scout",
    gender: "Male",
    birthday: "2025-04-02",
    adoptionDate: "2026-02-07",
    fosterLitter: 7,
    image: "assets/kittens/alumni-skylar.png",
    photos: [],
    secondChance: true
  },
  {
    id: "ruben",
    status: "Adopted",
    name: "Ruben",
    gender: "Male",
    birthday: "2025-03-23",
    adoptionDate: "2025-09-06",
    fosterLitter: 6,
    image: "assets/kittens/alumni-ruben.png",
    photos: [],
    companionId: "otto"
  },
  {
    id: "otto",
    status: "Adopted",
    name: "Otto",
    gender: "Male",
    birthday: "2025-03-23",
    adoptionDate: "2025-09-06",
    fosterLitter: 6,
    image: "assets/kittens/alumni-otto.png",
    photos: [],
    companionId: "ruben"
  },
  {
    id: "clementine",
    status: "Adopted",
    name: "Clementine",
    gender: "Female",
    birthday: "2025-03-23",
    adoptionDate: "2025-09-17",
    fosterLitter: 6,
    image: "assets/kittens/alumni-clementine.png",
    photos: [],
    companionId: "charlotte"
  },
  {
    id: "charlotte",
    status: "Adopted",
    name: "Charlotte",
    gender: "Female",
    birthday: "2025-03-23",
    adoptionDate: "2025-09-17",
    fosterLitter: 6,
    image: "assets/kittens/alumni-charlotte.png",
    photos: [],
    companionId: "clementine"
  },
  {
    id: "diablo",
    status: "Adopted",
    name: "Diablo",
    gender: "Male",
    birthday: "2024-11-13",
    adoptionDate: "2025-05-17",
    fosterLitter: 5,
    image: "assets/kittens/alumni-diablo.png",
    photos: []
  },
  {
    id: "lyra",
    status: "Adopted",
    name: "Lyra",
    gender: "Female",
    birthday: "2024-07-07",
    adoptionDate: "2024-10-27",
    fosterLitter: 3,
    image: "assets/kittens/alumni-lyra.png",
    photos: [],
    companionId: "hamlet"
  },
  {
    id: "hamlet",
    status: "Adopted",
    name: "Hamlet",
    gender: "Male",
    birthday: "2024-07-07",
    adoptionDate: "2024-10-27",
    fosterLitter: 3,
    image: "assets/kittens/alumni-hamlet.png",
    photos: [],
    companionId: "lyra"
  },
  {
    id: "iris",
    status: "Adopted",
    name: "Iris",
    gender: "Female",
    birthday: "2024-07-07",
    adoptionDate: "2024-11-16",
    fosterLitter: 3,
    image: "assets/kittens/alumni-iris.png",
    photos: [],
    companionId: "lucy"
  },
  {
    id: "lucy",
    status: "Adopted",
    name: "Lucy",
    gender: "Female",
    birthday: "2024-07-07",
    adoptionDate: "2024-11-16",
    fosterLitter: 3,
    image: "assets/kittens/alumni-lucy.png",
    photos: [],
    companionId: "iris"
  },
  {
    id: "marceline",
    status: "Adopted",
    name: "Marceline",
    gender: "Female",
    birthday: "2024-07-07",
    adoptionDate: "2024-12-21",
    fosterLitter: 3,
    image: "assets/kittens/alumni-marceline.png",
    photos: [],
    companionId: "finn"
  },
  {
    id: "finn",
    status: "Adopted",
    name: "Finn",
    gender: "Male",
    birthday: "2024-07-07",
    adoptionDate: "2024-12-21",
    fosterLitter: 4,
    image: "assets/kittens/alumni-finn.png",
    photos: [],
    companionId: "marceline"
  },
  {
    id: "mavis",
    status: "Adopted",
    name: "Mavis",
    gender: "Female",
    birthday: "2024-07-07",
    adoptionDate: "2025-04-27",
    fosterLitter: 3,
    image: "assets/kittens/alumni-mavis.png",
    photos: [],
    companionId: "fawn",
    secondChance: true
  },
  {
    id: "fawn",
    status: "Adopted",
    name: "Fawn",
    gender: "Female",
    birthday: "2024-07-07",
    adoptionDate: "2025-04-27",
    fosterLitter: 3,
    image: "assets/kittens/alumni-fawn.png",
    photos: [],
    companionId: "mavis",
    secondChance: true
  },
  {
    id: "oscar",
    status: "Adopted",
    name: "Oscar",
    gender: "Male",
    birthday: "2024-04-04",
    adoptionDate: "2024-08-10",
    fosterLitter: 2,
    image: "assets/kittens/alumni-oscar.png",
    photos: []
  },
  {
    id: "roscoe",
    status: "Adopted",
    name: "Roscoe",
    gender: "Male",
    birthday: "2024-04-04",
    adoptionDate: "2024-08-03",
    fosterLitter: 2,
    image: "assets/kittens/alumni-roscoe.png",
    photos: [],
    fosterFail: true
  },
  {
    id: "bea",
    status: "Adopted",
    name: "Bea",
    gender: "Female",
    birthday: "2024-04-04",
    adoptionDate: "2024-08-10",
    fosterLitter: 2,
    image: "assets/kittens/alumni-bea.png",
    photos: []
  },
  {
    id: "rosie",
    status: "Adopted",
    name: "Rosie",
    gender: "Female",
    birthday: "2024-01-12",
    adoptionDate: "2024-06-23",
    fosterLitter: 1,
    image: "assets/kittens/alumni-rosie.png",
    photos: [],
    companionId: "lily"
  },
  {
    id: "lily",
    status: "Adopted",
    name: "Lily",
    gender: "Female",
    birthday: "2024-01-12",
    adoptionDate: "2024-06-23",
    fosterLitter: 1,
    image: "assets/kittens/alumni-lily.png",
    photos: [],
    companionId: "rosie"
  },
  {
    id: "mouse",
    status: "Adopted",
    name: "Mouse",
    gender: "Male",
    birthday: "2024-01-12",
    adoptionDate: "2025-04-11",
    fosterLitter: 1,
    image: "assets/kittens/alumni-mouse.png",
    photos: []
  },
  {
    id: "smudge",
    status: "Adopted",
    name: "Smudge",
    gender: "Male",
    birthday: "2024-01-12",
    adoptionDate: "2024-04-23",
    fosterLitter: 1,
    image: "assets/kittens/alumni-smudge.png",
    photos: [],
    fosterFail: true
  }
];
