// ==========================================
// KITTEN CARDS AND PROFILE DETAILS — EDIT HERE
// Add one object per kitten. Use empty strings or [] for details not ready yet.
// Photos should live in assets/kittens/.
// ==========================================
const appRoot = typeof window !== "undefined" ? window : globalThis;

appRoot.PAWS_KITTEN_STATUSES = {
  AVAILABLE: "Available",
  RETURNED_AVAILABLE: "Returned — Available",
  PENDING_INTEREST: "Pending Interest",
  ALMOST_AVAILABLE: "Almost Available",
  PRE_ADOPTED: "Pre-Adopted",
  COMING_SOON: "Coming Soon",
  ADOPTED: "Adopted"
};

appRoot.PAWS_AVAILABLE_KITTEN_STATUSES = new Set([
  appRoot.PAWS_KITTEN_STATUSES.AVAILABLE,
  appRoot.PAWS_KITTEN_STATUSES.RETURNED_AVAILABLE,
  appRoot.PAWS_KITTEN_STATUSES.PENDING_INTEREST
]);

appRoot.PAWS_KITTENS = [
  {
    id: "diego",
    name: "Diego",
    status: "Available",
    adoptionStatus: "Available",
    description: "Diego is a super outgoing and playful kitten who loves being involved in every activity.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=diego",
    gender: "Male",
    birthday: "2026-03-24",
    litterNumber: 11,
    bio: "Meet Diego! He is a super outgoing and playful kitten who spends most of his time running, jumping, wrestling, and climbing with his siblings. Diego loves carrying toys in his mouth and showing them off to anyone. He is social, enjoys being around people, and always wants to be a part of whatever is going on. He loves attention and often puts himself right in the middle of everything just to be involved.",
    photos: [],
    personalityTraits: ["Outgoing", "Playful", "Social", "Active", "Attention-loving", "Loves other cats"],
    idealHome: "A home where he can be part of the action, with people around to play, explore, and cuddle.",
    compatibility: { dogs: "No", cats: "Yes — with proper introduction", youngerChildren: "Possibly — no direct experience", olderChildren: "Yes" },
    healthChecklist: ["Neutered", "Fully vaccinated", "Dewormed", "Flea treated", "Microchipped", "Fostered and socialized"],
    adoptionRequirements: [],
    petfinderUrl: "https://www.petfinder.com/cat/diego-050b5d9b-599c-4483-98fc-b2957135ac14/ca/oakley/no-paws-left-behind-kitty-rescue-ca3018/details/",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "valentina" }
  },
  {
    id: "valentina",
    name: "Valentina",
    status: "Available",
    adoptionStatus: "Available",
    description: "A confident and affectionate kitten who loves attention and keeps the room full of energy.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=valentina",
    gender: "Female",
    birthday: "",
    litterNumber: 11,
    bio: "Valentina is a confident kitten who enjoys being near people and soaking up attention. She is affectionate, curious, and full of personality.",
    photos: [],
    personalityTraits: ["Confident", "Affectionate", "Social", "Curious", "Playful", "Sweet"],
    idealHome: "A home with a warm, attentive family who appreciates a sweet, social companion.",
    compatibility: { dogs: "Unknown — no direct experience", cats: "Yes — with proper introduction", youngerChildren: "Possibly — no direct experience", olderChildren: "Yes" },
    healthChecklist: ["Spayed", "Fully vaccinated", "Dewormed", "Flea treated", "Microchipped", "Fostered and socialized"],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "diego" }
  },
  {
    id: "claudia",
    name: "Claudia",
    status: "Available",
    adoptionStatus: "Available",
    description: "A sweet kitten with a calm personality who enjoys quiet attention and gentle play.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=claudia",
    gender: "Female",
    birthday: "",
    litterNumber: 11,
    bio: "Claudia is gentle, sweet, and observant. She likes calm attention, quiet corners, and cozy moments with people she trusts.",
    photos: [],
    personalityTraits: ["Gentle", "Sweet", "Observant", "Calm", "Affectionate", "Curious"],
    idealHome: "A peaceful home with patient people and room for quiet cuddles and gentle play.",
    compatibility: { dogs: "Unknown — no direct experience", cats: "Yes — with proper introduction", youngerChildren: "Possibly — no direct experience", olderChildren: "Yes" },
    healthChecklist: ["Spayed", "Fully vaccinated", "Dewormed", "Flea treated", "Microchipped", "Fostered and socialized"],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "paloma" }
  },
  {
    id: "paloma",
    name: "Paloma",
    status: "Available",
    adoptionStatus: "Available",
    description: "A curious and friendly kitten who loves exploring and then settling in for cuddles.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=paloma",
    gender: "Female",
    birthday: "",
    litterNumber: 11,
    bio: "Paloma is curious, friendly, and cuddle-loving. She enjoys exploring and then winding down close to the people she loves.",
    photos: [],
    personalityTraits: ["Curious", "Friendly", "Cuddly", "Playful", "Social", "Sweet"],
    idealHome: "A warm home with gentle activity and plenty of opportunities to explore and settle in close to her people.",
    compatibility: { dogs: "Unknown — no direct experience", cats: "Yes — with proper introduction", youngerChildren: "Possibly — no direct experience", olderChildren: "Yes" },
    healthChecklist: ["Spayed", "Fully vaccinated", "Dewormed", "Flea treated", "Microchipped", "Fostered and socialized"],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "claudia" }
  },
  {
    id: "harvey",
    name: "Harvey",
    status: "Available",
    adoptionStatus: "Available",
    description: "A playful and people-focused kitten who is always ready to follow the action.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=harvey",
    gender: "Male",
    birthday: "",
    litterNumber: 12,
    bio: "Harvey is playful, bold, and social. He likes being in the middle of the fun and following his people wherever they go.",
    photos: [],
    personalityTraits: ["Playful", "Bold", "Social", "Outgoing", "Curious", "Active"],
    idealHome: "A home with regular interaction, toys, and room for a lively kitten to explore and play.",
    compatibility: { dogs: "Unknown — no direct experience", cats: "Yes — with proper introduction", youngerChildren: "Possibly — no direct experience", olderChildren: "Yes" },
    healthChecklist: ["Neutered", "Fully vaccinated", "Dewormed", "Flea treated", "Microchipped", "Fostered and socialized"],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "melody" }
  },
  {
    id: "melody",
    name: "Melody",
    status: "Available",
    adoptionStatus: "Available",
    description: "A bright, lively kitten with a sweet nature and an affectionate personality.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=melody",
    gender: "Female",
    birthday: "",
    litterNumber: 12,
    bio: "Melody is lively, affectionate, and playful. She brings energy and sweetness to every room she enters.",
    photos: [],
    personalityTraits: ["Lively", "Affectionate", "Playful", "Friendly", "Sweet", "Energetic"],
    idealHome: "A cheerful home with time for play, attention, and a kitten who loves to be part of everyday life.",
    compatibility: { dogs: "Unknown — no direct experience", cats: "Yes — with proper introduction", youngerChildren: "Possibly — no direct experience", olderChildren: "Yes" },
    healthChecklist: ["Spayed", "Fully vaccinated", "Dewormed", "Flea treated", "Microchipped", "Fostered and socialized"],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "harvey" }
  },
  {
    id: "wally",
    name: "Wally",
    status: "Available",
    adoptionStatus: "Available",
    description: "A curious kitten who enjoys exploring, playing, and making himself part of the family.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=wally",
    gender: "Male",
    birthday: "",
    litterNumber: 10,
    bio: "Wally is curious, funny, and outgoing. He loves exploring new spaces and then settling in with the people he adores.",
    photos: [],
    personalityTraits: ["Curious", "Funny", "Outgoing", "Social", "Active", "Playful"],
    idealHome: "A playful home where his curiosity and personality are welcomed every day.",
    compatibility: { dogs: "Unknown — no direct experience", cats: "Yes — with proper introduction", youngerChildren: "Possibly — no direct experience", olderChildren: "Yes" },
    healthChecklist: ["Neutered", "Fully vaccinated", "Dewormed", "Flea treated", "Microchipped", "Fostered and socialized"],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "raymond" }
  },
  {
    id: "raymond",
    name: "Raymond",
    status: "Available",
    adoptionStatus: "Available",
    description: "A gentle, social kitten who loves people and turns every room into a new adventure.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=raymond",
    gender: "Male",
    birthday: "",
    litterNumber: 10,
    bio: "Raymond is gentle, social, and playful. He enjoys being near people, especially when there is fun to be had.",
    photos: [],
    personalityTraits: ["Gentle", "Social", "Playful", "Affectionate", "Curious", "Sweet"],
    idealHome: "A calm home where he can be close to people and enjoy gentle play, cuddles, and companionship.",
    compatibility: { dogs: "Unknown — no direct experience", cats: "Yes — with proper introduction", youngerChildren: "Possibly — no direct experience", olderChildren: "Yes" },
    healthChecklist: ["Neutered", "Fully vaccinated", "Dewormed", "Flea treated", "Microchipped", "Fostered and socialized"],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "wally" }
  }
];

if (typeof module !== "undefined") {
  module.exports = {
    PAWS_KITTEN_STATUSES: appRoot.PAWS_KITTEN_STATUSES,
    PAWS_AVAILABLE_KITTEN_STATUSES: appRoot.PAWS_AVAILABLE_KITTEN_STATUSES,
    PAWS_KITTENS: appRoot.PAWS_KITTENS
  };
}
