// ==========================================
// KITTEN CARDS AND PROFILE DETAILS — EDIT HERE
// Add one object per kitten. Use empty strings or [] for details not ready yet.
// Photos should live in assets/kittens/.
// ==========================================
const appRoot = typeof window !== "undefined" ? window : globalThis;

appRoot.PAWS_KITTEN_STATUSES = {
  AVAILABLE: "Available",
  RETURNED_AVAILABLE: "Returned — Available",
  PENDING_INTEREST: "Pending Interest",
  ALMOST_AVAILABLE: "Almost Available",
  PRE_ADOPTED: "Pre-Adopted",
  COMING_SOON: "Coming Soon",
  ADOPTED: "Adopted"
};

appRoot.PAWS_AVAILABLE_KITTEN_STATUSES = new Set([
  appRoot.PAWS_KITTEN_STATUSES.AVAILABLE,
  appRoot.PAWS_KITTEN_STATUSES.RETURNED_AVAILABLE,
  appRoot.PAWS_KITTEN_STATUSES.PENDING_INTEREST,
  appRoot.PAWS_KITTEN_STATUSES.PRE_ADOPTED
]);

appRoot.PAWS_KITTENS = [
  {
    id: "diego",
    name: "Diego",
    status: "Available",
    adoptionStatus: "Available",
    description: "Diego is a super outgoing and playful kitten who loves being involved in every activity.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=diego",
    gender: "Male",
    birthday: "2026-03-24",
    litterNumber: "11",
    bio: "Meet Diego! He is a super outgoing and playful kitten who spends most of his time running, jumping, wrestling, and climbing with his siblings. Diego loves carrying toys in his mouth and showing them off to anyone. He is social, enjoys being around people, and always wants to be a part of whatever is going on. He loves attention and often puts himself right in the middle of everything just to be involved.",
    photos: [],
    personalityTraits: ["Outgoing", "Playful", "Social", "Active", "Attention-loving", "Loves other cats"],
    idealHome: "High-energy or low-energy home",
    compatibility: { dogs: "No dogs", cats: "Yes, with proper introduction", youngerChildren: "Possibly; no direct experience yet", olderChildren: "Yes" },
    healthChecklist: ["Neutered", "Vaccines up to date", "Dewormed", "Flea treated", "Microchipped", "Fostered/socialized", "Loved and cared for"],
    adoptionRequirements: [],
    petfinderUrl: "https://www.petfinder.com/cat/diego-050b5d9b-599c-4483-98fc-b2957135ac14/ca/oakley/no-paws-left-behind-kitty-rescue-ca3018/details/",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "valentina" }
  },
  {
    id: "valentina",
    name: "Valentina",
    status: "Available",
    adoptionStatus: "Available",
    description: "A confident and affectionate kitten who loves attention and keeps the room full of energy.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=valentina",
    gender: "Female",
    birthday: "",
    litterNumber: "",
    bio: "",
    photos: [],
    personalityTraits: ["Confident", "Affectionate", "Social"],
    idealHome: "",
    compatibility: { dogs: "", cats: "", youngerChildren: "", olderChildren: "" },
    healthChecklist: [],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "diego" }
  },
  {
    id: "claudia",
    name: "Claudia",
    status: "Available",
    adoptionStatus: "Available",
    description: "A sweet kitten with a calm personality who enjoys quiet attention and gentle play.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=claudia",
    gender: "Female",
    birthday: "",
    litterNumber: "",
    bio: "",
    photos: [],
    personalityTraits: ["Gentle", "Sweet", "Observant"],
    idealHome: "",
    compatibility: { dogs: "", cats: "", youngerChildren: "", olderChildren: "" },
    healthChecklist: [],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "paloma" }
  },
  {
    id: "paloma",
    name: "Paloma",
    status: "Available",
    adoptionStatus: "Available",
    description: "A curious and friendly kitten who loves exploring and then settling in for cuddles.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=paloma",
    gender: "Female",
    birthday: "",
    litterNumber: "",
    bio: "",
    photos: [],
    personalityTraits: ["Curious", "Friendly", "Cuddly"],
    idealHome: "",
    compatibility: { dogs: "", cats: "", youngerChildren: "", olderChildren: "" },
    healthChecklist: [],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "claudia" }
  },
  {
    id: "harvey",
    name: "Harvey",
    status: "Available",
    adoptionStatus: "Available",
    description: "A playful and people-focused kitten who is always ready to follow the action.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=harvey",
    gender: "Male",
    birthday: "",
    litterNumber: "",
    bio: "",
    photos: [],
    personalityTraits: ["Playful", "Bold", "Social"],
    idealHome: "",
    compatibility: { dogs: "", cats: "", youngerChildren: "", olderChildren: "" },
    healthChecklist: [],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "melody" }
  },
  {
    id: "melody",
    name: "Melody",
    status: "Available",
    adoptionStatus: "Available",
    description: "A bright, lively kitten with a sweet nature and an affectionate personality.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=melody",
    gender: "Female",
    birthday: "",
    litterNumber: "",
    bio: "",
    photos: [],
    personalityTraits: ["Lively", "Affectionate", "Playful"],
    idealHome: "",
    compatibility: { dogs: "", cats: "", youngerChildren: "", olderChildren: "" },
    healthChecklist: [],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "harvey" }
  },
  {
    id: "wally",
    name: "Wally",
    status: "Available",
    adoptionStatus: "Available",
    description: "A curious kitten who enjoys exploring, playing, and making himself part of the family.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=wally",
    gender: "Male",
    birthday: "",
    litterNumber: "",
    bio: "",
    photos: [],
    personalityTraits: ["Curious", "Funny", "Outgoing"],
    idealHome: "",
    compatibility: { dogs: "", cats: "", youngerChildren: "", olderChildren: "" },
    healthChecklist: [],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "raymond" }
  },
  {
    id: "raymond",
    name: "Raymond",
    status: "Available",
    adoptionStatus: "Available",
    description: "A gentle, social kitten who loves people and turns every room into a new adventure.",
    image: "",
    profileUrl: "kittens/profile-template.html?id=raymond",
    gender: "Male",
    birthday: "",
    litterNumber: "",
    bio: "",
    photos: [],
    personalityTraits: ["Gentle", "Social", "Playful"],
    idealHome: "",
    compatibility: { dogs: "", cats: "", youngerChildren: "", olderChildren: "" },
    healthChecklist: [],
    adoptionRequirements: [],
    petfinderUrl: "",
    whereToMeet: "",
    videoUrl: "",
    eventInformation: "",
    pairing: { type: "must", kittenId: "wally" }
  }
];

if (typeof module !== "undefined") {
  module.exports = {
    PAWS_KITTEN_STATUSES: appRoot.PAWS_KITTEN_STATUSES,
    PAWS_AVAILABLE_KITTEN_STATUSES: appRoot.PAWS_AVAILABLE_KITTEN_STATUSES,
    PAWS_KITTENS: appRoot.PAWS_KITTENS
  };
}
